
AWSTemplateFormatVersion: 2010-09-09
Description: Virginia-ec2

   


  



# Parameters:
#   SubnetID:
#     Description: chose subnet-dinamically
#     Type: String
#     Default: subnet-063b2efa3cbd8b7e1
#     AllowedValues:
#       - subnet-063b2efa3cbd8b7e1
#       - subnet-083bf7ab93601ab8b

# Mappings:
#   SubnetMap: 
#     us-east-1:
#       PublicSub:  subnet-063b2efa3cbd8b7e1   
#       PrivateSub: subnet-083bf7ab93601ab8b

  
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: virginia-kp
      SubnetId : subnet-063b2efa3cbd8b7e1
      ImageId: ami-0323c3dd2da7fb37d
      InstanceType: t2.micro
      
      Tags:
        - Key: Name
          Value: Virginia-Ec2-App           


   
 